spring:
  profiles:
    active: local
  thymeleaf:
    prefix : classpath:templates/
    suffix : .html
    cache : false
  rsocket:
    server:
      port: 7777
      transport: websocket
      mapping-path: /rs  
logging:
    level:
      root: info
      com.example: DEBUG
---
spring:
  config:
    activate:
      on-profile: local
  devtools:
    restart:
      enabled: true
server:
  title: ddc-local
  port : 8080

---
spring:
  config:
    activate:
      on-profile: prod
  devtools:
    restart:
      enabled: false
server:
  title: ddc-prod
  port : 8081